baseURL = "https://batmanian.github.io/keithdunstan/"
languageCode = "en-au"
title = "Keith Dunstan"
theme = "ace"
publishdir = "docs"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "This is the blog section"
    title = "blog section"
    url = "/blog/"
    weight = -110