#!/usr/bin/env node
// Regenerates src/_data/topics.md from every `tags:` entry found across the
// site's content files. Existing descriptions are preserved; newly-seen
// topics are appended with an empty description. Run with `npm run generate-topics`.

const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
const yaml = require("js-yaml");

const SRC_DIR = path.join(__dirname, "..", "src");
const OUTPUT_FILE = path.join(SRC_DIR, "_data", "topics.md");

// Mirrors the exclusion list used by the `tagList` collection in .eleventy.js
const EXCLUDED_TAGS = ["post", "all", "book", "books", "article", "articles"];

// Tags live in frontmatter on both .md content files and the handful of
// .njk book chapters (e.g. src/books/ratbags/*.njk) that carry them directly.
const CONTENT_EXTENSIONS = [".md", ".njk"];

function findContentFiles(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findContentFiles(fullPath));
    } else if (entry.isFile() && CONTENT_EXTENSIONS.includes(path.extname(entry.name)) && fullPath !== OUTPUT_FILE) {
      results.push(fullPath);
    }
  }
  return results;
}

function collectCurrentTopics() {
  const topics = new Set();
  for (const file of findContentFiles(SRC_DIR)) {
    let data;
    try {
      ({ data } = matter(fs.readFileSync(file, "utf8")));
    } catch (err) {
      console.warn(`Skipping ${path.relative(process.cwd(), file)}: ${err.message}`);
      continue;
    }
    if (!Array.isArray(data.tags)) continue;
    for (const tag of data.tags) {
      if (typeof tag === "string" && tag.trim() && !EXCLUDED_TAGS.includes(tag)) {
        topics.add(tag);
      }
    }
  }
  return topics;
}

function loadExistingDescriptions() {
  const descriptions = new Map();
  if (fs.existsSync(OUTPUT_FILE)) {
    const { data } = matter(fs.readFileSync(OUTPUT_FILE, "utf8"));
    for (const entry of data.topics || []) {
      if (entry && entry.name) {
        descriptions.set(entry.name, entry.description || "");
      }
    }
  }
  return descriptions;
}

function main() {
  const currentTopics = collectCurrentTopics();
  const existingDescriptions = loadExistingDescriptions();

  let addedCount = 0;
  const topics = Array.from(currentTopics)
    .sort((a, b) => a.localeCompare(b))
    .map(name => {
      if (!existingDescriptions.has(name)) addedCount++;
      return { name, description: existingDescriptions.get(name) || "" };
    });

  const frontmatter = yaml.dump({ topics }, { lineWidth: -1 });
  const body = `---\n${frontmatter}---\n\nGenerated by \`npm run generate-topics\` from every \`tags:\` entry across the site's content files. Re-running the script preserves existing \`description\` values and only appends topics it hasn't seen before — it never removes or overwrites one. Fill in \`description\` for each entry as time allows.\n`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, body);

  console.log(`Wrote ${topics.length} topics to ${path.relative(process.cwd(), OUTPUT_FILE)} (${addedCount} new).`);
}

main();
