#!/usr/bin/env node
// Regenerates src/_data/topics.md from every `tags:` entry found across the
// site's content files. Existing descriptions are preserved; newly-seen
// topics are appended with an empty description, but only once they reach
// MIN_ENTRIES_FOR_DESCRIPTION page entries — topics below that don't get a
// blank description queued up. A topic that already has a written
// description is always kept even if its entry count later drops below the
// threshold, so no manual work is ever thrown away. Run with `npm run generate-topics`.

const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
const yaml = require("js-yaml");

const SRC_DIR = path.join(__dirname, "..", "src");
const OUTPUT_FILE = path.join(SRC_DIR, "_data", "topics.md");

// Lower bound on page entries before a topic is worth queuing up a
// description for. Deliberately looser than the "more than 3 entries"
// threshold the topic cloud on /search.html uses to decide what to display
// (src/_includes/snippets/tagslist.njk) — a topic can be worth describing
// even if it doesn't yet have enough entries to appear in that browse list.
const MIN_ENTRIES_FOR_DESCRIPTION = 2;

// Mirrors the exclusion list used by the `tagList` collection in .eleventy.js
const EXCLUDED_TAGS = ["post", "all", "book", "books", "article", "articles"];

// Tags live in frontmatter on both .md content files and the handful of
// .njk book chapters (e.g. src/books/ratbags/*.njk) that carry them directly.
const CONTENT_EXTENSIONS = [".md", ".njk"];

function findContentFiles(dir) {
  let results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findContentFiles(fullPath));
    } else if (entry.isFile() && CONTENT_EXTENSIONS.includes(path.extname(entry.name)) && fullPath !== OUTPUT_FILE) {
      results.push(fullPath);
    }
  }
  return results;
}

function collectCurrentTopics() {
  const counts = new Map();
  for (const file of findContentFiles(SRC_DIR)) {
    let data;
    try {
      ({ data } = matter(fs.readFileSync(file, "utf8")));
    } catch (err) {
      console.warn(`Skipping ${path.relative(process.cwd(), file)}: ${err.message}`);
      continue;
    }
    if (!Array.isArray(data.tags)) continue;
    for (const tag of new Set(data.tags)) {
      if (typeof tag === "string" && tag.trim() && !EXCLUDED_TAGS.includes(tag)) {
        counts.set(tag, (counts.get(tag) || 0) + 1);
      }
    }
  }
  return counts;
}

function loadExistingDescriptions() {
  const descriptions = new Map();
  if (fs.existsSync(OUTPUT_FILE)) {
    const { data } = matter(fs.readFileSync(OUTPUT_FILE, "utf8"));
    for (const entry of data.topics || []) {
      if (entry && entry.name) {
        descriptions.set(entry.name, entry.description || "");
      }
    }
  }
  return descriptions;
}

function main() {
  const currentCounts = collectCurrentTopics();
  const existingDescriptions = loadExistingDescriptions();

  let addedCount = 0;
  let skippedCount = 0;
  // Union of tags currently in use and tags with a hand-written description
  // already on file — a topic keeps its description even if its tag has
  // since been removed from every content file, so existing work is never
  // silently dropped just because content changed underneath it.
  const allNames = new Set([...currentCounts.keys(), ...existingDescriptions.keys()]);
  const topics = Array.from(allNames)
    .filter(name => {
      const hasDescription = (existingDescriptions.get(name) || "").trim().length > 0;
      const meetsThreshold = (currentCounts.get(name) || 0) >= MIN_ENTRIES_FOR_DESCRIPTION;
      // Below-threshold topics only make the cut if they already carry
      // hand-written description work — never drop existing effort, but
      // never queue up new blank-description work for them either.
      if (!meetsThreshold && !hasDescription) {
        skippedCount++;
        return false;
      }
      return true;
    })
    .sort((a, b) => a.localeCompare(b))
    .map(name => {
      if (!existingDescriptions.has(name)) addedCount++;
      return { name, description: existingDescriptions.get(name) || "" };
    });

  const frontmatter = yaml.dump({ topics }, { lineWidth: -1 });
  const body = `---\n${frontmatter}---\n\nGenerated by \`npm run generate-topics\` from every \`tags:\` entry across the site's content files that has at least ${MIN_ENTRIES_FOR_DESCRIPTION} page entries (topics below that only appear here if they already have a hand-written description). Re-running the script preserves existing \`description\` values and only appends topics it hasn't seen before — it never removes or overwrites one. Fill in \`description\` for each entry as time allows.\n`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, body);

  console.log(`Wrote ${topics.length} topics to ${path.relative(process.cwd(), OUTPUT_FILE)} (${addedCount} new, ${skippedCount} below the ${MIN_ENTRIES_FOR_DESCRIPTION}-entry threshold and skipped).`);
}

main();
